#!/usr/bin/env node
// The modules a plugin UI bundle is built against in place of `svelte` and `@netpi/kit`: shims that read the copies
// the host UI exports on globalThis.__netpiHost (set in web/src/main.js). A tab bundle then carries no Svelte runtime
// and no kit copy of its own — one reactive system for the page (a `$derived` in a tab that reads host state tracks it
// today only because the tab has a private copy of svelte) and roughly half the bytes per tab.
//
// The export lists come from the installed svelte and from the kit's index, not from a hand-kept copy, so a svelte
// bump regenerates them with the build. Each shim checks that it is running inside a host UI, that the host's svelte is
// the one it was built against, and that the host exports everything it needs: a tab meeting a host it was not built
// for throws a message naming the cause, which the tab host shows with a Retry button, instead of a blank panel.
//
//   node web/scripts/host-shims.mjs         write them (build:plugins does this itself on every run)
//
// Generated files, never committed: artifacts/ is ignored and build-plugins rewrites them from what is installed.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const svelteDir = path.join(repo, 'node_modules/svelte');
const kitIndex = path.join(repo, 'web/src/lib/kit/index.js');
const outDir = path.join(repo, 'artifacts/web-shims');

/** The specifier each svelte shim answers to, and the source its export list is read from (bare `svelte` is the server entry under Node). */
const SVELTE_MODULES = [
  { file: 'svelte.js', spec: 'svelte', key: 'svelte', from: 'src/index-client.js' },
  { file: 'svelte-internal-client.js', spec: 'svelte/internal/client', key: 'client', from: 'src/internal/client/index.js' },
  { file: 'svelte-reactivity.js', spec: 'svelte/reactivity', key: 'reactivity', from: 'src/reactivity/index-client.js' },
];

const MISSING = "The NetPI UI running this tab does not export every export the tab was built against. Its UI build and this tab must come from the same svelte and the same kit; rebuild both (npm run build, npm run build:plugins).";

/**
 * The export names of an ES module that only declares or re-exports them (svelte's index files and the kit's index
 * are both flat lists of `export function x` / `export { a, b as c } from …`), read from the source text.
 */
export function exportNames(src) {
  const names = new Set();
  for (const m of src.matchAll(/^\s*export\s+(?:async\s+)?(?:function|class|const|let|var)\s+([\w$]+)/gm)) names.add(m[1]);
  for (const m of src.matchAll(/^\s*export\s*\{([^}]*)\}/gm))
    for (const spec of m[1].split(',')) {
      const parts = spec.trim().split(/\s+as\s+/);
      const name = (parts[1] ?? parts[0]).trim();
      if (name && name !== 'default') names.add(name);
    }
  return [...names].sort();
}

/** A local for an export: `if` and `await` are reserved words, and nothing may shadow the shim's own bindings. */
const local = (name) => `_${name.replace(/[^\w$]/g, '_')}`;

/**
 * A shim: the host's copy of `names`, behind the guard that makes a mismatch visible.
 *
 *   const { push: _push, if: _if } = client;
 *   const bound = { push: _push, if: _if };
 *   export { _push as push, _if as if };
 *
 * The destructuring is what lets a reserved word be exported at all (`export { _if as if }`; `export const if` is a
 * syntax error), and reading every name once at module load is also the check that the host exports all of them —
 * named, so a host that is missing one says which.
 */
function shim(guard, from, names) {
  const locals = names.map((n) => `${n}: ${local(n)}`);
  return `${guard}
const { ${locals.join(', ')} } = ${from};
const bound = { ${locals.join(', ')} };
const missing = Object.keys(bound).filter((name) => bound[name] === undefined);
if (missing.length) throw new Error(${JSON.stringify(MISSING)} + ' Missing: ' + missing.join(', ') + '.');
export { ${names.map((n) => `${local(n)} as ${n}`).join(', ')} };
`;
}

const header = (doc) => `// Generated by web/scripts/host-shims.mjs — do not edit.\n${doc.split('\n').map((l) => (l ? `// ${l}` : l)).join('\n')}\n`;

/** svelte's own version, which a tab bundle is pinned to: the shims refuse a host running another one. */
const svelteVersion = () => JSON.parse(fs.readFileSync(path.join(svelteDir, 'package.json'), 'utf8')).version;

/** Write every shim; returns them as alias entries for build-plugins. */
export function writeHostShims() {
  const version = svelteVersion();
  const write = (file, body) => {
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(path.join(outDir, file), body);
    return path.join(outDir, file);
  };

  const guard = `const runtime = globalThis.__netpiHost?.svelte;
if (!runtime)
  throw new Error(
    'This tab was built against a NetPI UI that shares its Svelte runtime, and the UI running it does not export one (globalThis.__netpiHost.svelte is unset). Restore the UI build the tab was built with, or rebuild the tab against this NetPI (npm run build:plugins).',
  );
if (runtime.version !== '${version}')
  throw new Error(
    \`Svelte version skew: this tab was built against svelte ${version}, the host runs svelte \${runtime.version}. Reload the page (the host may have been updated); if it still fails, rebuild the tab (npm run build:plugins).\`,
  );`;

  const entries = SVELTE_MODULES.map(({ file, spec, key, from }) => [
    spec,
    write(
      file,
      header(`A plugin tab bundle's \`${spec}\`: the host UI's own svelte ${version} (globalThis.__netpiHost.svelte).`) +
        shim(guard, `runtime.${key}`, exportNames(fs.readFileSync(path.join(svelteDir, from), 'utf8'))),
    ),
  ]);

  // The compiler emits this import in every component; the host UI discloses its own version when it starts.
  entries.push([
    'svelte/internal/disclose-version',
    write(
      'svelte-disclose-version.js',
      header('Nothing to disclose: the host UI (globalThis.__netpiHost.svelte.version) is the svelte this tab runs on, and it discloses it itself when it starts.') +
        'export {};\n',
    ),
  ]);

  entries.push([
    '@netpi/kit',
    write(
      'kit.js',
      header("A plugin tab bundle's `@netpi/kit`: the host UI's own kit components and helpers, so a tab bundle carries no copy of them.") +
        shim(
          `const kit = globalThis.__netpiHost?.kit;
if (!kit)
  throw new Error(
    "This tab was built against a NetPI UI that shares its kit components, and the UI running it does not export them (globalThis.__netpiHost.kit is unset). Restore the UI build the tab was built with, or rebuild the tab against this NetPI (npm run build:plugins).",
  );`,
          'kit',
          exportNames(fs.readFileSync(kitIndex, 'utf8')),
        ),
    ),
  ]);

  // Anchored: vite matches an alias anywhere in the specifier, so bare `svelte` would claim `svelte/internal/client`
  // and rewrite it to the shim's own path with the rest of the specifier appended.
  return { aliases: entries.map(([find, replacement]) => ({ find: new RegExp(`^${find.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}$`), replacement })), version };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { aliases, version } = writeHostShims();
  for (const { find, replacement } of aliases) console.log(`  ${find.source} → ${path.relative(repo, replacement)} (svelte ${version})`);
}
